/**
 * Core domain types for the bridge. Nothing in `src/core` may import `vscode`,
 * so the whole routing/transport layer stays unit-testable in plain Node.
 */

/**
 * `paused` is internal: it labels the expiry notice a session posts when it goes idle so
 * the thread does not render a red "Failed" heading for a normal lifecycle event. It is
 * deliberately kept out of the notify tool's public status enum, because "paused" is a
 * bridge-owned state, not something a caller reports.
 */
export type NotificationStatus = 'completed' | 'needs-input' | 'failed' | 'progress' | 'paused';

/**
 * Which kind of Copilot surface owns a session.
 *
 * A reply has to be handed back through the same surface that started the work, and each
 * one is reached differently. Recording the surface at creation is what lets a reply be
 * routed to it instead of being guessed at afterwards.
 */
export type HarnessKind =
	/** Copilot Chat panel or editor inside VS Code. */
	| 'vscode-sidebar'
	/** An agent session in VS Code, which reaches the bridge over MCP. */
	| 'vscode-agent-mcp'
	/** The Copilot CLI runtime hosted inside VS Code. */
	| 'cli-runtime'
	/** Another MCP client entirely, which this extension cannot deliver into. */
	| 'external'
	/** Not established. Never treated as a guess — replies are held instead. */
	| 'unknown';

/** How to reach a specific conversation within a harness. */
export interface ChatHandle {
	kind: 'chat-session-resource' | 'cli-debug-log' | 'none';
	value: string;
}

/**
 * Who owns a session, recorded when it is created rather than derived later.
 *
 * The chat that starts a session is knowable at that moment — the transcript filename is
 * the chat id, and an in-process tool call carries `sessionResource`. Discarding it and
 * searching transcripts afterwards is what made delivery a guess, and a wrong guess puts
 * one task's instruction into another task's conversation.
 */
export interface SessionIdentity {
	harness: HarnessKind;
	chat?: ChatHandle;
	/**
	 * `exact` — the host handed it to us.
	 * `derived` — inferred from a transcript, good enough to deliver.
	 * `unknown` — not established; hold the reply rather than guess.
	 */
	confidence: 'exact' | 'derived' | 'unknown';
	capturedBy: 'chat-watcher' | 'notify-tool' | 'mcp-ingest' | 'resolver';
	capturedAt: string;
}

/** What last kept a session alive, which the sliding idle window is measured from. */
export type ActivitySource = 'teams-reply' | 'chat-turn' | 'notify' | 'revival';

/** A Copilot Chat session mapped onto exactly one Teams thread. */
export interface Session {
	/** Stable id generated by the bridge. */
	id: string;
	/** Caller supplied key (usually the task name) used to reuse a thread across tool calls. */
	key: string;
	/** Human readable subject of the Teams thread. */
	title: string;
	/** Transport specific thread handle, assigned on the first notification. */
	thread?: ThreadRef;
	workspace?: string;
	createdAt: string;
	lastActivityAt: string;
	/**
	 * Which surface owns this session and how to reach its conversation.
	 *
	 * Optional so records written by an older build still load; a missing identity is read
	 * as `unknown`, which holds replies rather than guessing at them.
	 */
	identity?: SessionIdentity;
	/** What last kept the session alive, so the sliding window can be explained. */
	lastActivitySource?: ActivitySource;
	/**
	 * When the user was told that replies here cannot reach Copilot.
	 *
	 * Recorded so the point is made once rather than on every reply: a harness this window
	 * cannot deliver into will not become deliverable by waiting, so repeating the notice
	 * would only bury the thread the updates are arriving in.
	 */
	unreachableNoticeAt?: string;
	/** ISO timestamp of the newest reply consumed from this thread. */
	lastReplyAt?: string;
	/**
	 * Set when the session went idle past its window and the user was warned in Teams.
	 * An expired session is no longer polled until it is explicitly extended.
	 */
	expiredAt?: string;
	/** Ids of replies already delivered, used for de-duplication. */
	seenReplyIds: string[];
	status: NotificationStatus;
	closed?: boolean;
	/**
	 * Identifies the Copilot Chat session that opened this thread, when the host revealed it.
	 * Used to steer a reply back to the chat that started the work instead of whichever one
	 * happens to be focused.
	 */
	chatSessionResource?: string;
	/**
	 * Replies collected but not yet handed to anyone.
	 *
	 * Persisted because the background poller marks a reply seen and advances the watermark
	 * as it collects, so holding it only in memory would lose it for good if the process
	 * stopped before an agent asked — which is exactly what happens when a turn ends.
	 */
	pending?: PendingReply[];
	/**
	 * Ids of replies already handed to a chat.
	 *
	 * Two processes write this file: one adds to the queue, the other empties it. Neither
	 * can tell a reply the other removed from one it has not seen yet, so a removal is
	 * recorded rather than implied. Without it a stale writer restores what was delivered
	 * and the instruction is injected again and again.
	 */
	deliveredReplyIds?: string[];
	/**
	 * Request ids of chat turns already summarised into this thread.
	 *
	 * Persisted rather than kept in memory because the transcript is rescanned from the
	 * start on every write and after every reload: without a record of what has already
	 * been posted, reloading the window would replay the whole conversation into Teams.
	 */
	postedTurnIds?: string[];
	/**
	 * When the model last reported this session to Teams itself.
	 *
	 * A notify call made during a turn is a deliberate, better-written update than anything
	 * that can be salvaged from the transcript, so the automatic per-turn summary stands
	 * down for that turn rather than saying the same thing twice in different words.
	 */
	lastNotifyAt?: string;
	/**
	 * Replies the user has already been told are waiting.
	 *
	 * A retained reply is retried on every poll, and each attempt would otherwise repeat
	 * the same notice into Teams — turning one undelivered instruction into a wall of
	 * identical failures every ten seconds.
	 */
	noticedReplyIds?: string[];
}

/** A reply that has been read from Teams but not yet delivered. */
export interface PendingReply {
	reply: InboundReply;
	/** Cleaned instruction text, with any leading slash command removed. */
	text: string;
	command?: string;
}

/** Identifies a Teams thread (a channel root message and its replies). */
export interface ThreadRef {
	/** Transport-specific thread id. For Graph this is the root message id. */
	id: string;
	/** Deep link to the thread, shown in the UI when available. */
	webUrl?: string;
}

export interface OutboundNotification {
	sessionId: string;
	title: string;
	summary: string;
	status: NotificationStatus;
	question?: string;
	files?: string[];
	workspace?: string;
	/** True when the session is blocked waiting for a Teams reply. */
	awaitingReply?: boolean;
	/**
	 * Whether a reply in this thread can actually reach Copilot.
	 *
	 * Undefined means yes, so existing callers are unaffected. Set to false for a harness
	 * the extension cannot deliver into — a CLI session, or any client outside this VS Code
	 * window — so the message says so instead of inviting a reply that will go nowhere.
	 */
	repliesReachChat?: boolean;
	/**
	 * When `repliesReachChat` is false, which harness the session runs in.
	 *
	 * Optional: the footer needs a different sentence for a CLI-hosted agent (queued for it
	 * to pick up on the next check) than for a fully external client (nothing here can
	 * reach it), and this is the piece of information the renderer needs to tell them apart.
	 * A missing value falls back to the generic "will not reach Copilot" wording.
	 */
	unreachableHarness?: HarnessKind;
}

export interface InboundReply {
	/** Transport message id, unique within the thread. Used as the de-duplication key. */
	id: string;
	threadId: string;
	text: string;
	from: string;
	createdAt: string;
}

export interface PostResult {
	thread: ThreadRef;
	/**
	 * Id of the message just posted, when the transport exposes one. The bridge marks it as
	 * seen so Copilot's own follow-up messages are never mistaken for user replies (with
	 * delegated auth the bot posts as the same user who replies).
	 */
	postedMessageId?: string;
}

// Ports -- ThreadedTransport, SessionStore and BridgeLogger -- live in
// application/ports: they describe what the application needs from the outside world,
// which is not something the domain should know about.
